# Generated by Django 4.0.4 on 2022-04-20 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(max_length=100, verbose_name='Book Category')),
                ('slug', models.SlugField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, default='Unknown', help_text='Name of Author to avoid Plagiarisation', max_length=20000, verbose_name='Book Author')),
                ('title', models.CharField(max_length=2000)),
                ('slug', models.SlugField(max_length=2000)),
                ('summary', models.TextField()),
                ('isbn', models.PositiveIntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('author_web', models.URLField(blank=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookapp.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Upload by')),
            ],
        ),
    ]
