# Generated by Django 4.0.4 on 2022-04-20 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0002_remove_book_category_book_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='docs',
            field=models.FileField(blank=True, upload_to='docs'),
        ),
        migrations.AddField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='images'),
        ),
    ]
