# Generated by Django 4.0.4 on 2022-04-21 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0003_book_docs_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='docs',
            field=models.FileField(blank=True, upload_to='docs', verbose_name='Upload document'),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='images', verbose_name='upload'),
        ),
    ]
